/*
 * This file is generated by jOOQ.
 */
package uk.co.markg.mimic.db.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import uk.co.markg.mimic.db.tables.Messages;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MessagesRecord extends UpdatableRecordImpl<MessagesRecord> implements Record5<Long, Long, String, Long, Long> {

    private static final long serialVersionUID = 353539439;

    /**
     * Setter for <code>messages.messageid</code>.
     */
    public void setMessageid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>messages.messageid</code>.
     */
    public Long getMessageid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>messages.userid</code>.
     */
    public void setUserid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>messages.userid</code>.
     */
    public Long getUserid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>messages.content</code>.
     */
    public void setContent(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>messages.content</code>.
     */
    public String getContent() {
        return (String) get(2);
    }

    /**
     * Setter for <code>messages.channelid</code>.
     */
    public void setChannelid(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>messages.channelid</code>.
     */
    public Long getChannelid() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>messages.serverid</code>.
     */
    public void setServerid(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>messages.serverid</code>.
     */
    public Long getServerid() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Long, String, Long, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, Long, String, Long, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Messages.MESSAGES.MESSAGEID;
    }

    @Override
    public Field<Long> field2() {
        return Messages.MESSAGES.USERID;
    }

    @Override
    public Field<String> field3() {
        return Messages.MESSAGES.CONTENT;
    }

    @Override
    public Field<Long> field4() {
        return Messages.MESSAGES.CHANNELID;
    }

    @Override
    public Field<Long> field5() {
        return Messages.MESSAGES.SERVERID;
    }

    @Override
    public Long component1() {
        return getMessageid();
    }

    @Override
    public Long component2() {
        return getUserid();
    }

    @Override
    public String component3() {
        return getContent();
    }

    @Override
    public Long component4() {
        return getChannelid();
    }

    @Override
    public Long component5() {
        return getServerid();
    }

    @Override
    public Long value1() {
        return getMessageid();
    }

    @Override
    public Long value2() {
        return getUserid();
    }

    @Override
    public String value3() {
        return getContent();
    }

    @Override
    public Long value4() {
        return getChannelid();
    }

    @Override
    public Long value5() {
        return getServerid();
    }

    @Override
    public MessagesRecord value1(Long value) {
        setMessageid(value);
        return this;
    }

    @Override
    public MessagesRecord value2(Long value) {
        setUserid(value);
        return this;
    }

    @Override
    public MessagesRecord value3(String value) {
        setContent(value);
        return this;
    }

    @Override
    public MessagesRecord value4(Long value) {
        setChannelid(value);
        return this;
    }

    @Override
    public MessagesRecord value5(Long value) {
        setServerid(value);
        return this;
    }

    @Override
    public MessagesRecord values(Long value1, Long value2, String value3, Long value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MessagesRecord
     */
    public MessagesRecord() {
        super(Messages.MESSAGES);
    }

    /**
     * Create a detached, initialised MessagesRecord
     */
    public MessagesRecord(Long messageid, Long userid, String content, Long channelid, Long serverid) {
        super(Messages.MESSAGES);

        set(0, messageid);
        set(1, userid);
        set(2, content);
        set(3, channelid);
        set(4, serverid);
    }
}
