/*
 * This file is generated by jOOQ.
 */
package uk.co.markg.mimic.db.tables.records;


import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;

import uk.co.markg.mimic.db.tables.Users;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRecord extends TableRecordImpl<UsersRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = 2058005540;

    /**
     * Setter for <code>users.userid</code>.
     */
    public void setUserid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>users.userid</code>.
     */
    public Long getUserid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>users.serverid</code>.
     */
    public void setServerid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>users.serverid</code>.
     */
    public Long getServerid() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Users.USERS.USERID;
    }

    @Override
    public Field<Long> field2() {
        return Users.USERS.SERVERID;
    }

    @Override
    public Long component1() {
        return getUserid();
    }

    @Override
    public Long component2() {
        return getServerid();
    }

    @Override
    public Long value1() {
        return getUserid();
    }

    @Override
    public Long value2() {
        return getServerid();
    }

    @Override
    public UsersRecord value1(Long value) {
        setUserid(value);
        return this;
    }

    @Override
    public UsersRecord value2(Long value) {
        setServerid(value);
        return this;
    }

    @Override
    public UsersRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(Long userid, Long serverid) {
        super(Users.USERS);

        set(0, userid);
        set(1, serverid);
    }
}
