/*
 * This file is generated by jOOQ.
 */
package uk.co.markg.mimic.db.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Channels implements Serializable {

    private static final long serialVersionUID = 805265014;

    private Long    channelid;
    private Boolean readPerm;
    private Boolean writePerm;
    private Long    serverid;

    public Channels() {}

    public Channels(Channels value) {
        this.channelid = value.channelid;
        this.readPerm = value.readPerm;
        this.writePerm = value.writePerm;
        this.serverid = value.serverid;
    }

    public Channels(
        Long    channelid,
        Boolean readPerm,
        Boolean writePerm,
        Long    serverid
    ) {
        this.channelid = channelid;
        this.readPerm = readPerm;
        this.writePerm = writePerm;
        this.serverid = serverid;
    }

    public Long getChannelid() {
        return this.channelid;
    }

    public void setChannelid(Long channelid) {
        this.channelid = channelid;
    }

    public Boolean getReadPerm() {
        return this.readPerm;
    }

    public void setReadPerm(Boolean readPerm) {
        this.readPerm = readPerm;
    }

    public Boolean getWritePerm() {
        return this.writePerm;
    }

    public void setWritePerm(Boolean writePerm) {
        this.writePerm = writePerm;
    }

    public Long getServerid() {
        return this.serverid;
    }

    public void setServerid(Long serverid) {
        this.serverid = serverid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Channels (");

        sb.append(channelid);
        sb.append(", ").append(readPerm);
        sb.append(", ").append(writePerm);
        sb.append(", ").append(serverid);

        sb.append(")");
        return sb.toString();
    }
}
