/*
 * This file is generated by jOOQ.
 */
package uk.co.markg.mimic.db.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ServerConfig implements Serializable {

    private static final long serialVersionUID = 428938055;

    private Long   serverid;
    private String optInRole;

    public ServerConfig() {}

    public ServerConfig(ServerConfig value) {
        this.serverid = value.serverid;
        this.optInRole = value.optInRole;
    }

    public ServerConfig(
        Long   serverid,
        String optInRole
    ) {
        this.serverid = serverid;
        this.optInRole = optInRole;
    }

    public Long getServerid() {
        return this.serverid;
    }

    public void setServerid(Long serverid) {
        this.serverid = serverid;
    }

    public String getOptInRole() {
        return this.optInRole;
    }

    public void setOptInRole(String optInRole) {
        this.optInRole = optInRole;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ServerConfig (");

        sb.append(serverid);
        sb.append(", ").append(optInRole);

        sb.append(")");
        return sb.toString();
    }
}
