/*
 * This file is generated by jOOQ.
 */
package uk.co.markg.mimic.db.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Usage implements Serializable {

    private static final long serialVersionUID = 942235014;

    private Integer       id;
    private String        command;
    private Long          serverid;
    private LocalDateTime usagetime;

    public Usage() {}

    public Usage(Usage value) {
        this.id = value.id;
        this.command = value.command;
        this.serverid = value.serverid;
        this.usagetime = value.usagetime;
    }

    public Usage(
        Integer       id,
        String        command,
        Long          serverid,
        LocalDateTime usagetime
    ) {
        this.id = id;
        this.command = command;
        this.serverid = serverid;
        this.usagetime = usagetime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCommand() {
        return this.command;
    }

    public void setCommand(String command) {
        this.command = command;
    }

    public Long getServerid() {
        return this.serverid;
    }

    public void setServerid(Long serverid) {
        this.serverid = serverid;
    }

    public LocalDateTime getUsagetime() {
        return this.usagetime;
    }

    public void setUsagetime(LocalDateTime usagetime) {
        this.usagetime = usagetime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Usage (");

        sb.append(id);
        sb.append(", ").append(command);
        sb.append(", ").append(serverid);
        sb.append(", ").append(usagetime);

        sb.append(")");
        return sb.toString();
    }
}
