/*
 * This file is generated by jOOQ.
 */
package uk.co.markg.mimic.db.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements Serializable {

    private static final long serialVersionUID = 1179612963;

    private Long userid;
    private Long serverid;

    public Users() {}

    public Users(Users value) {
        this.userid = value.userid;
        this.serverid = value.serverid;
    }

    public Users(
        Long userid,
        Long serverid
    ) {
        this.userid = userid;
        this.serverid = serverid;
    }

    public Long getUserid() {
        return this.userid;
    }

    public void setUserid(Long userid) {
        this.userid = userid;
    }

    public Long getServerid() {
        return this.serverid;
    }

    public void setServerid(Long serverid) {
        this.serverid = serverid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(userid);
        sb.append(", ").append(serverid);

        sb.append(")");
        return sb.toString();
    }
}
