/*
 * This file is generated by jOOQ.
 */
package uk.co.markg.bertrand.db.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Channels implements Serializable {

    private static final long serialVersionUID = 239020034;

    private Long channelid;

    public Channels() {}

    public Channels(Channels value) {
        this.channelid = value.channelid;
    }

    public Channels(
        Long channelid
    ) {
        this.channelid = channelid;
    }

    public Long getChannelid() {
        return this.channelid;
    }

    public void setChannelid(Long channelid) {
        this.channelid = channelid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Channels (");

        sb.append(channelid);

        sb.append(")");
        return sb.toString();
    }
}
