/*
 * This file is generated by jOOQ.
 */
package uk.co.markg.bertrand.db.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Messages implements Serializable {

    private static final long serialVersionUID = 1787510309;

    private Long   messageid;
    private Long   userid;
    private String content;

    public Messages() {}

    public Messages(Messages value) {
        this.messageid = value.messageid;
        this.userid = value.userid;
        this.content = value.content;
    }

    public Messages(
        Long   messageid,
        Long   userid,
        String content
    ) {
        this.messageid = messageid;
        this.userid = userid;
        this.content = content;
    }

    public Long getMessageid() {
        return this.messageid;
    }

    public void setMessageid(Long messageid) {
        this.messageid = messageid;
    }

    public Long getUserid() {
        return this.userid;
    }

    public void setUserid(Long userid) {
        this.userid = userid;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Messages (");

        sb.append(messageid);
        sb.append(", ").append(userid);
        sb.append(", ").append(content);

        sb.append(")");
        return sb.toString();
    }
}
