version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - mvn package
artifacts:
  files:
    - target/bertrand-1.0.jar
    - appspec.yml
  discard-paths: yes