/*
 * This file is generated by jOOQ.
 */
package uk.co.markg.mimic.db;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import uk.co.markg.mimic.db.tables.Messages;
import uk.co.markg.mimic.db.tables.Users;


/**
 * A class modelling indexes of tables of the <code></code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CONTENT_MESSAGE_INDEX = Indexes0.CONTENT_MESSAGE_INDEX;
    public static final Index USER_MESSAGE_INDEX = Indexes0.USER_MESSAGE_INDEX;
    public static final Index USERS_PKEY = Indexes0.USERS_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index CONTENT_MESSAGE_INDEX = Internal.createIndex("content_message_index", Messages.MESSAGES, new OrderField[] { Messages.MESSAGES.CONTENT }, false);
        public static Index USER_MESSAGE_INDEX = Internal.createIndex("user_message_index", Messages.MESSAGES, new OrderField[] { Messages.MESSAGES.USERID }, false);
        public static Index USERS_PKEY = Internal.createIndex("users_pkey", Users.USERS, new OrderField[] { Users.USERS.USERID, Users.USERS.SERVERID }, true);
    }
}
