/*
 * This file is generated by jOOQ.
 */
package uk.co.markg.mimic.db;


import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import uk.co.markg.mimic.db.tables.Channels;
import uk.co.markg.mimic.db.tables.Messages;
import uk.co.markg.mimic.db.tables.ServerConfig;
import uk.co.markg.mimic.db.tables.Usage;
import uk.co.markg.mimic.db.tables.records.ChannelsRecord;
import uk.co.markg.mimic.db.tables.records.MessagesRecord;
import uk.co.markg.mimic.db.tables.records.ServerConfigRecord;
import uk.co.markg.mimic.db.tables.records.UsageRecord;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code></code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<UsageRecord, Integer> IDENTITY_USAGE = Identities0.IDENTITY_USAGE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChannelsRecord> CHANNELS_PKEY = UniqueKeys0.CHANNELS_PKEY;
    public static final UniqueKey<MessagesRecord> MESSAGES_PKEY = UniqueKeys0.MESSAGES_PKEY;
    public static final UniqueKey<ServerConfigRecord> SERVER_CONFIG_PKEY = UniqueKeys0.SERVER_CONFIG_PKEY;
    public static final UniqueKey<UsageRecord> USAGE_PKEY = UniqueKeys0.USAGE_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<MessagesRecord, ChannelsRecord> MESSAGES__CHANNEL_FKEY = ForeignKeys0.MESSAGES__CHANNEL_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<UsageRecord, Integer> IDENTITY_USAGE = Internal.createIdentity(Usage.USAGE, Usage.USAGE.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<ChannelsRecord> CHANNELS_PKEY = Internal.createUniqueKey(Channels.CHANNELS, "channels_pkey", new TableField[] { Channels.CHANNELS.CHANNELID }, true);
        public static final UniqueKey<MessagesRecord> MESSAGES_PKEY = Internal.createUniqueKey(Messages.MESSAGES, "messages_pkey", new TableField[] { Messages.MESSAGES.MESSAGEID }, true);
        public static final UniqueKey<ServerConfigRecord> SERVER_CONFIG_PKEY = Internal.createUniqueKey(ServerConfig.SERVER_CONFIG, "server_config_pkey", new TableField[] { ServerConfig.SERVER_CONFIG.SERVERID }, true);
        public static final UniqueKey<UsageRecord> USAGE_PKEY = Internal.createUniqueKey(Usage.USAGE, "usage_pkey", new TableField[] { Usage.USAGE.ID }, true);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<MessagesRecord, ChannelsRecord> MESSAGES__CHANNEL_FKEY = Internal.createForeignKey(Keys.CHANNELS_PKEY, Messages.MESSAGES, "channel_fkey", new TableField[] { Messages.MESSAGES.CHANNELID }, true);
    }
}
