/*
 * This file is generated by jOOQ.
 */
package uk.co.markg.mimic.db;


import uk.co.markg.mimic.db.tables.Channels;
import uk.co.markg.mimic.db.tables.Messages;
import uk.co.markg.mimic.db.tables.ServerConfig;
import uk.co.markg.mimic.db.tables.Usage;
import uk.co.markg.mimic.db.tables.Users;


/**
 * Convenience access to all tables in 
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>channels</code>.
     */
    public static final Channels CHANNELS = Channels.CHANNELS;

    /**
     * The table <code>messages</code>.
     */
    public static final Messages MESSAGES = Messages.MESSAGES;

    /**
     * The table <code>server_config</code>.
     */
    public static final ServerConfig SERVER_CONFIG = ServerConfig.SERVER_CONFIG;

    /**
     * The table <code>usage</code>.
     */
    public static final Usage USAGE = Usage.USAGE;

    /**
     * The table <code>users</code>.
     */
    public static final Users USERS = Users.USERS;
}
