/*
 * This file is generated by jOOQ.
 */
package uk.co.markg.bertrand.db.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;

import uk.co.markg.bertrand.db.tables.Channels;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChannelsRecord extends UpdatableRecordImpl<ChannelsRecord> implements Record1<Long> {

    private static final long serialVersionUID = 1266802166;

    /**
     * Setter for <code>channels.channelid</code>.
     */
    public void setChannelid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>channels.channelid</code>.
     */
    public Long getChannelid() {
        return (Long) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row1<Long> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    public Row1<Long> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Channels.CHANNELS.CHANNELID;
    }

    @Override
    public Long component1() {
        return getChannelid();
    }

    @Override
    public Long value1() {
        return getChannelid();
    }

    @Override
    public ChannelsRecord value1(Long value) {
        setChannelid(value);
        return this;
    }

    @Override
    public ChannelsRecord values(Long value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChannelsRecord
     */
    public ChannelsRecord() {
        super(Channels.CHANNELS);
    }

    /**
     * Create a detached, initialised ChannelsRecord
     */
    public ChannelsRecord(Long channelid) {
        super(Channels.CHANNELS);

        set(0, channelid);
    }
}
